# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

KEYCHAIN_NAME = ENV["KEYCHAIN_NAME"]
KEYCHAIN_PASSWORD = ENV["KEYCHAIN_PASSWORD"]

default_platform(:ios)

  desc "Save To Keychain"
  lane :set_keychain do |options|
    create_keychain(
      name: "#{KEYCHAIN_NAME}",
      password: "#{KEYCHAIN_PASSWORD}",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
end

platform :ios do
  desc "Push to TestFlight"
  lane :tf  do

    app_store_connect_api_key(is_key_content_base64: true, in_house: false)

     match(
      git_url: "git@github.com:kimkyuchul/Jumak-fastlane-certificate.git",
      storage_mode: "git",
      type: "appstore",
      readonly: true,
      keychain_name: "#{KEYCHAIN_NAME}",
      keychain_password: "#{KEYCHAIN_PASSWORD}"
    )
    
    match(
      git_url: "git@github.com:kimkyuchul/Jumak-fastlane-certificate.git",
      storage_mode: "git",
      type: "development",
      readonly: true,
      keychain_name: "#{KEYCHAIN_NAME}",
      keychain_password: "#{KEYCHAIN_PASSWORD}"
    )

  increment_build_number(
	 build_number: latest_testflight_build_number() + 1
    )
 
  cocoapods(clean_install: true, use_bundle_exec: false) 
  build_app(configuration: "Debug")

  upload_to_testflight(skip_waiting_for_build_processing: true)

  end
end
