# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: TestFlight

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  upload_testflight:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2


          
    # match 사용시 ssh-key 설정!
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    # Config 등 파일 가져와야 할 시 사용
    - name: Bring ignored files
      uses: actions/checkout@v3
      with:
        repository: kimkyuchul/Jumak-iOS-ignored
        path: Makgulli/Common/Resource
        token: ${{ secrets.ACTION_TOKEN }}
    
    - name: Install Fastlane
      run: brew install fastlane

    - name: Set Keychain
      run: fastlane set_keychain
      env:
        KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

    - name: Run Fastlane tf
      run: fastlane tf
      env:
        KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
        APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
        APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
